package br.com.qualicorp.redenarede.webservice.stub.beneficiario;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1-b03-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "AutenticacaoBeneficiarioServicePortType", targetNamespace = "http://service.autenticacao.ws.tempoassist.com.br")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AutenticacaoBeneficiarioServicePortType {


    /**
     * 
     * @param parameters
     * @return
     *     returns br.com.qualicorp.redenarede.webservice.stub.beneficiario.AutenticarResponse
     * @throws AutenticacaoBeneficiarioService
     */
    @WebMethod(action = "urn:autenticar")
    @WebResult(name = "autenticarResponse", targetNamespace = "http://service.autenticacao.ws.tempoassist.com.br", partName = "parameters")
    @Action(input = "urn:autenticarRequest", output = "urn:autenticarResponse")
    public AutenticarResponse autenticar(
        @WebParam(name = "autenticar", targetNamespace = "http://service.autenticacao.ws.tempoassist.com.br", partName = "parameters")
        Autenticar parameters)
        throws AutenticacaoBeneficiarioService
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns br.com.qualicorp.redenarede.webservice.stub.beneficiario.CriarSenhaResponse
     * @throws AutenticacaoBeneficiarioService
     */
    @WebMethod(action = "urn:criarSenha")
    @WebResult(name = "criarSenhaResponse", targetNamespace = "http://service.autenticacao.ws.tempoassist.com.br", partName = "parameters")
    @Action(input = "urn:criarSenhaRequest", output = "urn:criarSenhaResponse")
    public CriarSenhaResponse criarSenha(
        @WebParam(name = "criarSenha", targetNamespace = "http://service.autenticacao.ws.tempoassist.com.br", partName = "parameters")
        CriarSenha parameters)
        throws AutenticacaoBeneficiarioService
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns br.com.qualicorp.redenarede.webservice.stub.beneficiario.CriarSenhaGspResponse
     * @throws AutenticacaoBeneficiarioService
     */
    @WebMethod(action = "urn:criarSenhaGsp")
    @WebResult(name = "criarSenhaGspResponse", targetNamespace = "http://service.autenticacao.ws.tempoassist.com.br", partName = "parameters")
    @Action(input = "urn:criarSenhaGspRequest", output = "urn:criarSenhaGspResponse")
    public CriarSenhaGspResponse criarSenhaGsp(
        @WebParam(name = "criarSenhaGsp", targetNamespace = "http://service.autenticacao.ws.tempoassist.com.br", partName = "parameters")
        CriarSenhaGsp parameters)
        throws AutenticacaoBeneficiarioService
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns br.com.qualicorp.redenarede.webservice.stub.beneficiario.RecuperarSenhaResponse
     * @throws AutenticacaoBeneficiarioService
     */
    @WebMethod(action = "urn:recuperarSenha")
    @WebResult(name = "recuperarSenhaResponse", targetNamespace = "http://service.autenticacao.ws.tempoassist.com.br", partName = "parameters")
    @Action(input = "urn:recuperarSenhaRequest", output = "urn:recuperarSenhaResponse")
    public RecuperarSenhaResponse recuperarSenha(
        @WebParam(name = "recuperarSenha", targetNamespace = "http://service.autenticacao.ws.tempoassist.com.br", partName = "parameters")
        RecuperarSenha parameters)
        throws AutenticacaoBeneficiarioService
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns br.com.qualicorp.redenarede.webservice.stub.beneficiario.TrocarSenhaResponse
     * @throws AutenticacaoBeneficiarioService
     */
    @WebMethod(action = "urn:trocarSenha")
    @WebResult(name = "trocarSenhaResponse", targetNamespace = "http://service.autenticacao.ws.tempoassist.com.br", partName = "parameters")
    @Action(input = "urn:trocarSenhaRequest", output = "urn:trocarSenhaResponse")
    public TrocarSenhaResponse trocarSenha(
        @WebParam(name = "trocarSenha", targetNamespace = "http://service.autenticacao.ws.tempoassist.com.br", partName = "parameters")
        TrocarSenha parameters)
        throws AutenticacaoBeneficiarioService
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns br.com.qualicorp.redenarede.webservice.stub.beneficiario.ConsultarTokenResponse
     * @throws AutenticacaoBeneficiarioService
     */
    @WebMethod(action = "urn:consultarToken")
    @WebResult(name = "consultarTokenResponse", targetNamespace = "http://service.autenticacao.ws.tempoassist.com.br", partName = "parameters")
    @Action(input = "urn:consultarTokenRequest", output = "urn:consultarTokenResponse")
    public ConsultarTokenResponse consultarToken(
        @WebParam(name = "consultarToken", targetNamespace = "http://service.autenticacao.ws.tempoassist.com.br", partName = "parameters")
        ConsultarToken parameters)
        throws AutenticacaoBeneficiarioService
    ;

    
    @WebMethod(action = "urn:atualizarBeneficiario")
    @WebResult(name = "atualizarBeneficiarioResponse", targetNamespace = "http://service.autenticacao.ws.tempoassist.com.br", partName = "parameters")
    @Action(input = "urn:atualizarBeneficiarioRequest", output = "urn:atualizarBeneficiarioResponse")
    public AtualizarBeneficiarioResponse atualizarBeneficiario(
        @WebParam(name = "atualizarBeneficiario", targetNamespace = "http://service.autenticacao.ws.tempoassist.com.br", partName = "parameters")
        AtualizarBeneficiario params)
        throws AutenticacaoBeneficiarioService
    ;
}
