
package br.com.qualicorp.redenarede.webservice.stub.pretador;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1-b03-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "IServicoPrestador", targetNamespace = "http://tempuri.org/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IServicoPrestador {


    /**
     * 
     * @param parameters
     * @return
     *     returns br.com.qualicorp.redenarede.webservice.stub.pretador.ValidarUsuarioPrestadorResponse
     */
    @WebMethod(operationName = "ValidarUsuarioPrestador", action = "http://tempuri.org/IServicoPrestador/ValidarUsuarioPrestador")
    @WebResult(name = "ValidarUsuarioPrestadorResponse", targetNamespace = "http://tempuri.org/", partName = "parameters")
    @Action(input = "http://tempuri.org/IServicoPrestador/ValidarUsuarioPrestador", output = "http://tempuri.org/IServicoPrestador/ValidarUsuarioPrestadorResponse")
    public ValidarUsuarioPrestadorResponse validarUsuarioPrestador(
        @WebParam(name = "ValidarUsuarioPrestador", targetNamespace = "http://tempuri.org/", partName = "parameters")
        ValidarUsuarioPrestador parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns br.com.qualicorp.redenarede.webservice.stub.pretador.CadastrarUsuarioPrestadorResponse
     */
    @WebMethod(operationName = "CadastrarUsuarioPrestador", action = "http://tempuri.org/IServicoPrestador/CadastrarUsuarioPrestador")
    @WebResult(name = "CadastrarUsuarioPrestadorResponse", targetNamespace = "http://tempuri.org/", partName = "parameters")
    @Action(input = "http://tempuri.org/IServicoPrestador/CadastrarUsuarioPrestador", output = "http://tempuri.org/IServicoPrestador/CadastrarUsuarioPrestadorResponse")
    public CadastrarUsuarioPrestadorResponse cadastrarUsuarioPrestador(
        @WebParam(name = "CadastrarUsuarioPrestador", targetNamespace = "http://tempuri.org/", partName = "parameters")
        CadastrarUsuarioPrestador parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns br.com.qualicorp.redenarede.webservice.stub.pretador.AlterarSenhaUsuarioPrestadorResponse
     */
    @WebMethod(operationName = "AlterarSenhaUsuarioPrestador", action = "http://tempuri.org/IServicoPrestador/AlterarSenhaUsuarioPrestador")
    @WebResult(name = "AlterarSenhaUsuarioPrestadorResponse", targetNamespace = "http://tempuri.org/", partName = "parameters")
    @Action(input = "http://tempuri.org/IServicoPrestador/AlterarSenhaUsuarioPrestador", output = "http://tempuri.org/IServicoPrestador/AlterarSenhaUsuarioPrestadorResponse")
    public AlterarSenhaUsuarioPrestadorResponse alterarSenhaUsuarioPrestador(
        @WebParam(name = "AlterarSenhaUsuarioPrestador", targetNamespace = "http://tempuri.org/", partName = "parameters")
        AlterarSenhaUsuarioPrestador parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns br.com.qualicorp.redenarede.webservice.stub.pretador.RecuperarSenhaUsuarioPrestadorResponse
     */
    @WebMethod(operationName = "RecuperarSenhaUsuarioPrestador", action = "http://tempuri.org/IServicoPrestador/RecuperarSenhaUsuarioPrestador")
    @WebResult(name = "RecuperarSenhaUsuarioPrestadorResponse", targetNamespace = "http://tempuri.org/", partName = "parameters")
    @Action(input = "http://tempuri.org/IServicoPrestador/RecuperarSenhaUsuarioPrestador", output = "http://tempuri.org/IServicoPrestador/RecuperarSenhaUsuarioPrestadorResponse")
    public RecuperarSenhaUsuarioPrestadorResponse recuperarSenhaUsuarioPrestador(
        @WebParam(name = "RecuperarSenhaUsuarioPrestador", targetNamespace = "http://tempuri.org/", partName = "parameters")
        RecuperarSenhaUsuarioPrestador parameters);

}
